# Generated by Django 2.2.8 on 2020-05-30 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('package', '0006_reviewpackage'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewpackage',
            name='created_on',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
